import { PublicKey } from "@solana/web3.js";


const BTC_USD_SWITCHBOARD_AGGREGATOR = new PublicKey("8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee");
const USDC_USD_SWITCHBOARD_AGGREGATOR = new PublicKey("BjUgj6YCnFBZ49wF54ddBVA9qu8TeqkFtkbqmZcee8uW");
const XTZ_USD_SWITCHBOARD_AGGREGATOR = new PublicKey("F11LACseaLXuRaPSvnD6w15vSPHtx73YaGZv9293rQQm");

export const SWITCHBOARD_AGGREGATORS = [
    BTC_USD_SWITCHBOARD_AGGREGATOR,
    USDC_USD_SWITCHBOARD_AGGREGATOR,
    XTZ_USD_SWITCHBOARD_AGGREGATOR,
];